In [1]:
import numpy as np
arr = np.arange(0,11)

In [2]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [6]:
arr[6:]

array([ 6,  7,  8,  9, 10])

In [7]:
arr[0:5] = 100 #brodcasting using numpy arrays

In [8]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [10]:
arr_2d


array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [11]:
arr_2d[2,1] #nice way to index 2d arrays

40

In [12]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [13]:
arr = np.arange(1,11)

In [14]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
bool_arr = arr > 5 

In [17]:
arr[bool_arr] # very interesting !! 

array([ 6,  7,  8,  9, 10])

In [18]:
arr[arr < 3]

array([1, 2])

In [19]:
arr_2d = np.arange(50).reshape(10,5)

In [20]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [21]:
arr_2d[arr_2d < 9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])