# Introduction to Numpy Arrays

In [8]:
my_list= [1,2,3]

In [5]:
import numpy as np

In [9]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [14]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [15]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

The above is a 2D array :: list of lists to numpy array

## Code for readily generating a numpy array

In [18]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [20]:
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [21]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [23]:
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

### finding 10 evenly spaced points between 0-5

In [25]:
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

Now let us find 5 equally distributed numbers between 0 and 10

In [26]:
np.linspace(0,10,5)

array([  0. ,   2.5,   5. ,   7.5,  10. ])

Notice that the distribution values includes 0 , and 10

Creating an Identity Matrix

In [28]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [29]:
np.random.rand(5)

array([ 0.76714933,  0.72515765,  0.38315878,  0.86330018,  0.66391899])

outputs 5 random numbers between 0 & 1

In [30]:
np.random.rand(5,5)

array([[ 0.0278185 ,  0.94810937,  0.4643751 ,  0.82884127,  0.59733684],
       [ 0.00870781,  0.20752181,  0.19122635,  0.60268433,  0.94508989],
       [ 0.92081165,  0.77224365,  0.92818367,  0.38620238,  0.03404783],
       [ 0.19775   ,  0.85354688,  0.28529024,  0.43424333,  0.76857315],
       [ 0.45329825,  0.90198396,  0.76321464,  0.18061979,  0.95786319]])

The above values consider UNIFORM distribution . 
To have random values from standard normal distribution i.e centered at 0, use randn

In [31]:
np.random.randn(5)

array([ 0.48772478,  0.19950619, -0.43864047,  1.34947927,  0.52990584])

## Returning random integers from a low to a high number

In [34]:
np.random.randint(1,5,2) # low-val,high-val,Number-of-randoms-you-want

array([4, 3])

## Reshaping arrays

In [39]:
arr = np.arange(25)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
arr.max() #finding the max value in an array

24

In [43]:
arr.argmax() # finding the position of the max element

24

In [44]:
ranarr.argmin()

0

In [49]:
arr.shape

(25,)

(25,) --> the ',' indicates that arr was just a 1 dimentional vector

In [50]:
arr = arr.reshape(5,5)
arr.shape

(5, 5)

In [51]:
arr.dtype #finding out the datatype of an array

dtype('int64')